# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from snyk_python_sdk import schemas  # noqa: F401


class BulkPackageUrlsRequestBodyData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "attributes",
        }
        
        class properties:
        
            @staticmethod
            def attributes() -> typing.Type['BulkPackageUrlsRequestBodyDataAttributes']:
                return BulkPackageUrlsRequestBodyDataAttributes
        
            @staticmethod
            def type() -> typing.Type['Types']:
                return Types
            __annotations__ = {
                "attributes": attributes,
                "type": type,
            }
    
    attributes: 'BulkPackageUrlsRequestBodyDataAttributes'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> 'BulkPackageUrlsRequestBodyDataAttributes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> 'Types': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", "type", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> 'BulkPackageUrlsRequestBodyDataAttributes': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> typing.Union['Types', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", "type", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        attributes: 'BulkPackageUrlsRequestBodyDataAttributes',
        type: typing.Union['Types', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'BulkPackageUrlsRequestBodyData':
        return super().__new__(
            cls,
            *args,
            attributes=attributes,
            type=type,
            _configuration=_configuration,
            **kwargs,
        )

from snyk_python_sdk.model.bulk_package_urls_request_body_data_attributes import BulkPackageUrlsRequestBodyDataAttributes
from snyk_python_sdk.model.types import Types
