# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from snyk_python_sdk import schemas  # noqa: F401


class CoordinateVTwo(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "representations",
        }
        
        class properties:
        
            @staticmethod
            def representations() -> typing.Type['CoordinateVTwoRepresentations']:
                return CoordinateVTwoRepresentations
        
            @staticmethod
            def remedies() -> typing.Type['CoordinateVTwoRemedies']:
                return CoordinateVTwoRemedies
            __annotations__ = {
                "representations": representations,
                "remedies": remedies,
            }
    
    representations: 'CoordinateVTwoRepresentations'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["representations"]) -> 'CoordinateVTwoRepresentations': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["remedies"]) -> 'CoordinateVTwoRemedies': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["representations", "remedies", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["representations"]) -> 'CoordinateVTwoRepresentations': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["remedies"]) -> typing.Union['CoordinateVTwoRemedies', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["representations", "remedies", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        representations: 'CoordinateVTwoRepresentations',
        remedies: typing.Union['CoordinateVTwoRemedies', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'CoordinateVTwo':
        return super().__new__(
            cls,
            *args,
            representations=representations,
            remedies=remedies,
            _configuration=_configuration,
            **kwargs,
        )

from snyk_python_sdk.model.coordinate_v_two_remedies import CoordinateVTwoRemedies
from snyk_python_sdk.model.coordinate_v_two_representations import CoordinateVTwoRepresentations
