# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from snyk_python_sdk import schemas  # noqa: F401


class Dependency(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "package_version",
            "package_name",
        }
        
        class properties:
            
            
            class package_name(
                schemas.StrSchema
            ):
                pass
            
            
            class package_version(
                schemas.StrSchema
            ):
                pass
            __annotations__ = {
                "package_name": package_name,
                "package_version": package_version,
            }
    
    package_version: MetaOapg.properties.package_version
    package_name: MetaOapg.properties.package_name
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["package_name"]) -> MetaOapg.properties.package_name: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["package_version"]) -> MetaOapg.properties.package_version: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["package_name", "package_version", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["package_name"]) -> MetaOapg.properties.package_name: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["package_version"]) -> MetaOapg.properties.package_version: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["package_name", "package_version", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        package_version: typing.Union[MetaOapg.properties.package_version, str, ],
        package_name: typing.Union[MetaOapg.properties.package_name, str, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Dependency':
        return super().__new__(
            cls,
            *args,
            package_version=package_version,
            package_name=package_name,
            _configuration=_configuration,
            **kwargs,
        )
