# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from snyk_python_sdk import schemas  # noqa: F401


class PublicTargetRelationships(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "organization",
            "integration",
        }
        
        class properties:
        
            @staticmethod
            def integration() -> typing.Type['PublicTargetRelationshipsIntegration']:
                return PublicTargetRelationshipsIntegration
        
            @staticmethod
            def organization() -> typing.Type['PublicTargetRelationshipsOrganization']:
                return PublicTargetRelationshipsOrganization
            __annotations__ = {
                "integration": integration,
                "organization": organization,
            }
    
    organization: 'PublicTargetRelationshipsOrganization'
    integration: 'PublicTargetRelationshipsIntegration'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["integration"]) -> 'PublicTargetRelationshipsIntegration': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["organization"]) -> 'PublicTargetRelationshipsOrganization': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["integration", "organization", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["integration"]) -> 'PublicTargetRelationshipsIntegration': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["organization"]) -> 'PublicTargetRelationshipsOrganization': ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["integration", "organization", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        organization: 'PublicTargetRelationshipsOrganization',
        integration: 'PublicTargetRelationshipsIntegration',
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'PublicTargetRelationships':
        return super().__new__(
            cls,
            *args,
            organization=organization,
            integration=integration,
            _configuration=_configuration,
            **kwargs,
        )

from snyk_python_sdk.model.public_target_relationships_integration import PublicTargetRelationshipsIntegration
from snyk_python_sdk.model.public_target_relationships_organization import PublicTargetRelationshipsOrganization
