# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from snyk_python_sdk import schemas  # noqa: F401


class ServiceAccountsUpdateGroupNameByIdResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "attributes",
            "id",
            "type",
        }
        
        class properties:
        
            @staticmethod
            def attributes() -> typing.Type['ServiceAccountsUpdateGroupNameByIdResponseDataAttributes']:
                return ServiceAccountsUpdateGroupNameByIdResponseDataAttributes
            id = schemas.UUIDSchema
            type = schemas.StrSchema
        
            @staticmethod
            def links() -> typing.Type['ServiceAccountsUpdateGroupNameByIdResponseDataLinks']:
                return ServiceAccountsUpdateGroupNameByIdResponseDataLinks
            __annotations__ = {
                "attributes": attributes,
                "id": id,
                "type": type,
                "links": links,
            }
    
    attributes: 'ServiceAccountsUpdateGroupNameByIdResponseDataAttributes'
    id: MetaOapg.properties.id
    type: MetaOapg.properties.type
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["attributes"]) -> 'ServiceAccountsUpdateGroupNameByIdResponseDataAttributes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["links"]) -> 'ServiceAccountsUpdateGroupNameByIdResponseDataLinks': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["attributes", "id", "type", "links", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["attributes"]) -> 'ServiceAccountsUpdateGroupNameByIdResponseDataAttributes': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["id"]) -> MetaOapg.properties.id: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["type"]) -> MetaOapg.properties.type: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["links"]) -> typing.Union['ServiceAccountsUpdateGroupNameByIdResponseDataLinks', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["attributes", "id", "type", "links", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        attributes: 'ServiceAccountsUpdateGroupNameByIdResponseDataAttributes',
        id: typing.Union[MetaOapg.properties.id, str, uuid.UUID, ],
        type: typing.Union[MetaOapg.properties.type, str, ],
        links: typing.Union['ServiceAccountsUpdateGroupNameByIdResponseDataLinks', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ServiceAccountsUpdateGroupNameByIdResponseData':
        return super().__new__(
            cls,
            *args,
            attributes=attributes,
            id=id,
            type=type,
            links=links,
            _configuration=_configuration,
            **kwargs,
        )

from snyk_python_sdk.model.service_accounts_update_group_name_by_id_response_data_attributes import ServiceAccountsUpdateGroupNameByIdResponseDataAttributes
from snyk_python_sdk.model.service_accounts_update_group_name_by_id_response_data_links import ServiceAccountsUpdateGroupNameByIdResponseDataLinks
