# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from snyk_python_sdk.paths.orgs_org_id_settings_sast.get import GetForOrgRaw
from snyk_python_sdk.paths.orgs_org_id_settings_sast.patch import ToggleSnykCodeSettingsRaw


class SastSettingsApiRaw(
    GetForOrgRaw,
    ToggleSnykCodeSettingsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
