# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from snyk_python_sdk.paths.orgs_org_id_projects_project_id_sbom.get import GetProjectDocument
from snyk_python_sdk.apis.tags.sbom_api_raw import SBOMApiRaw


class SBOMApi(
    GetProjectDocument,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SBOMApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SBOMApiRaw(api_client)
