# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from snyk_python_sdk.paths.orgs_org_id_slack_app_tenant_id_channels_channel_id.get import GetChannelNameByIdRaw
from snyk_python_sdk.paths.orgs_org_id_slack_app_tenant_id_channels.get import GetChannelsRaw


class SlackApiRaw(
    GetChannelNameByIdRaw,
    GetChannelsRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
