# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from snyk_python_sdk.paths.orgs_org_id_targets_target_id.delete import DeleteByIdRaw
from snyk_python_sdk.paths.orgs_org_id_targets_target_id.get import GetByIdRaw
from snyk_python_sdk.paths.orgs_org_id_targets.get import ListByOrgIdRaw


class TargetsApiRaw(
    DeleteByIdRaw,
    GetByIdRaw,
    ListByOrgIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
