# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.projects_update_by_project_id_response_data_relationships_importer_data import ProjectsUpdateByProjectIdResponseDataRelationshipsImporterData
from snyk_python_sdk import configuration


class TestProjectsUpdateByProjectIdResponseDataRelationshipsImporterData(unittest.TestCase):
    """ProjectsUpdateByProjectIdResponseDataRelationshipsImporterData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
