# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_create_install_secret403_response_errors_item import AppsCreateInstallSecret403ResponseErrorsItem
from snyk_python_sdk import configuration


class TestAppsCreateInstallSecret403ResponseErrorsItem(unittest.TestCase):
    """AppsCreateInstallSecret403ResponseErrorsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
