# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_create_organization_app401_response_jsonapi import AppsCreateOrganizationApp401ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsCreateOrganizationApp401ResponseJsonapi(unittest.TestCase):
    """AppsCreateOrganizationApp401ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
