# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.patch_project_request_data_relationships_owner_data import PatchProjectRequestDataRelationshipsOwnerData
from snyk_python_sdk import configuration


class TestPatchProjectRequestDataRelationshipsOwnerData(unittest.TestCase):
    """PatchProjectRequestDataRelationshipsOwnerData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
