# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_install_group_app403_response_errors_item_source import AppsInstallGroupApp403ResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestAppsInstallGroupApp403ResponseErrorsItemSource(unittest.TestCase):
    """AppsInstallGroupApp403ResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
