# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_get_active_sessions400_response_errors_item_meta import AppsGetActiveSessions400ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsGetActiveSessions400ResponseErrorsItemMeta(unittest.TestCase):
    """AppsGetActiveSessions400ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
