# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_apps401_response_jsonapi import AppsListApps401ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsListApps401ResponseJsonapi(unittest.TestCase):
    """AppsListApps401ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
