# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_org_creations409_response_jsonapi import AppsListOrgCreations409ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsListOrgCreations409ResponseJsonapi(unittest.TestCase):
    """AppsListOrgCreations409ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
