# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_by_install_id_response import AppsByInstallIdResponse
from snyk_python_sdk import configuration


class TestAppsByInstallIdResponse(unittest.TestCase):
    """AppsByInstallIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
