# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_delete_app_by_id409_response_errors_item_meta import AppsDeleteAppById409ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsDeleteAppById409ResponseErrorsItemMeta(unittest.TestCase):
    """AppsDeleteAppById409ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
