# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_group_app_installs400_response_errors import AppsListGroupAppInstalls400ResponseErrors
from snyk_python_sdk import configuration


class TestAppsListGroupAppInstalls400ResponseErrors(unittest.TestCase):
    """AppsListGroupAppInstalls400ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
