# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_org_creations400_response_errors import AppsListOrgCreations400ResponseErrors
from snyk_python_sdk import configuration


class TestAppsListOrgCreations400ResponseErrors(unittest.TestCase):
    """AppsListOrgCreations400ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
