# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_get_by_client_id401_response_jsonapi import AppsGetByClientId401ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsGetByClientId401ResponseJsonapi(unittest.TestCase):
    """AppsGetByClientId401ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
