# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_apps400_response import AppsListApps400Response
from snyk_python_sdk import configuration


class TestAppsListApps400Response(unittest.TestCase):
    """AppsListApps400Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
