# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_create_organization_app_response_errors_item_source import AppsCreateOrganizationAppResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestAppsCreateOrganizationAppResponseErrorsItemSource(unittest.TestCase):
    """AppsCreateOrganizationAppResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
