# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_get_by_client_id409_response import AppsGetByClientId409Response
from snyk_python_sdk import configuration


class TestAppsGetByClientId409Response(unittest.TestCase):
    """AppsGetByClientId409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
