# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_update_attributes400_response_jsonapi import AppsUpdateAttributes400ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsUpdateAttributes400ResponseJsonapi(unittest.TestCase):
    """AppsUpdateAttributes400ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
