# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_update_creation_attributes_by_id500_response import AppsUpdateCreationAttributesById500Response
from snyk_python_sdk import configuration


class TestAppsUpdateCreationAttributesById500Response(unittest.TestCase):
    """AppsUpdateCreationAttributesById500Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
