# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.iac_settings_update_for_org_request import IacSettingsUpdateForOrgRequest
from snyk_python_sdk import configuration


class TestIacSettingsUpdateForOrgRequest(unittest.TestCase):
    """IacSettingsUpdateForOrgRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
