# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.service_accounts_update_organization_service_account_name_request import ServiceAccountsUpdateOrganizationServiceAccountNameRequest
from snyk_python_sdk import configuration


class TestServiceAccountsUpdateOrganizationServiceAccountNameRequest(unittest.TestCase):
    """ServiceAccountsUpdateOrganizationServiceAccountNameRequest unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
