# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_revoke_user_app_session500_response_errors_item import AppsRevokeUserAppSession500ResponseErrorsItem
from snyk_python_sdk import configuration


class TestAppsRevokeUserAppSession500ResponseErrorsItem(unittest.TestCase):
    """AppsRevokeUserAppSession500ResponseErrorsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
