# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_group_app_installs409_response_errors_item_source import AppsListGroupAppInstalls409ResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestAppsListGroupAppInstalls409ResponseErrorsItemSource(unittest.TestCase):
    """AppsListGroupAppInstalls409ResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
