# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_update_attributes403_response_errors_item_source import AppsUpdateAttributes403ResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestAppsUpdateAttributes403ResponseErrorsItemSource(unittest.TestCase):
    """AppsUpdateAttributes403ResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
