# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_get_by_app_id409_response_errors import AppsGetByAppId409ResponseErrors
from snyk_python_sdk import configuration


class TestAppsGetByAppId409ResponseErrors(unittest.TestCase):
    """AppsGetByAppId409ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
