# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.service_accounts_manage_client_secret_request_data_attributes import ServiceAccountsManageClientSecretRequestDataAttributes
from snyk_python_sdk import configuration


class TestServiceAccountsManageClientSecretRequestDataAttributes(unittest.TestCase):
    """ServiceAccountsManageClientSecretRequestDataAttributes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
