# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_apps404_response_errors_item_meta import AppsListApps404ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsListApps404ResponseErrorsItemMeta(unittest.TestCase):
    """AppsListApps404ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
