# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.service_accounts_list_group_service_accounts_response_data_item_links import ServiceAccountsListGroupServiceAccountsResponseDataItemLinks
from snyk_python_sdk import configuration


class TestServiceAccountsListGroupServiceAccountsResponseDataItemLinks(unittest.TestCase):
    """ServiceAccountsListGroupServiceAccountsResponseDataItemLinks unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
