# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_create_new_app_for_organization403_response_errors_item_meta import AppsCreateNewAppForOrganization403ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsCreateNewAppForOrganization403ResponseErrorsItemMeta(unittest.TestCase):
    """AppsCreateNewAppForOrganization403ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
