# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.container_image_list_image_target_refs_response import ContainerImageListImageTargetRefsResponse
from snyk_python_sdk import configuration


class TestContainerImageListImageTargetRefsResponse(unittest.TestCase):
    """ContainerImageListImageTargetRefsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
