# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_install_group_app404_response_jsonapi import AppsInstallGroupApp404ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsInstallGroupApp404ResponseJsonapi(unittest.TestCase):
    """AppsInstallGroupApp404ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
