# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_get_by_app_id500_response_errors_item_meta import AppsGetByAppId500ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsGetByAppId500ResponseErrorsItemMeta(unittest.TestCase):
    """AppsGetByAppId500ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
