# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.projects_get_by_project_id_response_data_relationships_organization_data import ProjectsGetByProjectIdResponseDataRelationshipsOrganizationData
from snyk_python_sdk import configuration


class TestProjectsGetByProjectIdResponseDataRelationshipsOrganizationData(unittest.TestCase):
    """ProjectsGetByProjectIdResponseDataRelationshipsOrganizationData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
