# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_install_snyk_app_to_org404_response_errors import AppsInstallSnykAppToOrg404ResponseErrors
from snyk_python_sdk import configuration


class TestAppsInstallSnykAppToOrg404ResponseErrors(unittest.TestCase):
    """AppsInstallSnykAppToOrg404ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
