# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.common_issue_model_v_two_attributes_problems_item import CommonIssueModelVTwoAttributesProblemsItem
from snyk_python_sdk import configuration


class TestCommonIssueModelVTwoAttributesProblemsItem(unittest.TestCase):
    """CommonIssueModelVTwoAttributesProblemsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
