# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.container_image_get_instance_response import ContainerImageGetInstanceResponse
from snyk_python_sdk import configuration


class TestContainerImageGetInstanceResponse(unittest.TestCase):
    """ContainerImageGetInstanceResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
