# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_manage_client_secret_for_snyk_app409_response import AppsManageClientSecretForSnykApp409Response
from snyk_python_sdk import configuration


class TestAppsManageClientSecretForSnykApp409Response(unittest.TestCase):
    """AppsManageClientSecretForSnykApp409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
