# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_get_active_sessions401_response import AppsGetActiveSessions401Response
from snyk_python_sdk import configuration


class TestAppsGetActiveSessions401Response(unittest.TestCase):
    """AppsGetActiveSessions401Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
