# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_revoke_bot_authorization403_response_jsonapi import AppsRevokeBotAuthorization403ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsRevokeBotAuthorization403ResponseJsonapi(unittest.TestCase):
    """AppsRevokeBotAuthorization403ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
