# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.targets_get_by_id_response import TargetsGetByIdResponse
from snyk_python_sdk import configuration


class TestTargetsGetByIdResponse(unittest.TestCase):
    """TargetsGetByIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
