# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_create_install_secret400_response_jsonapi import AppsCreateInstallSecret400ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsCreateInstallSecret400ResponseJsonapi(unittest.TestCase):
    """AppsCreateInstallSecret400ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
