# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_update_attributes404_response_errors import AppsUpdateAttributes404ResponseErrors
from snyk_python_sdk import configuration


class TestAppsUpdateAttributes404ResponseErrors(unittest.TestCase):
    """AppsUpdateAttributes404ResponseErrors unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
