# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.hello_world_attributes_request_subject import HelloWorldAttributesRequestSubject
from snyk_python_sdk import configuration


class TestHelloWorldAttributesRequestSubject(unittest.TestCase):
    """HelloWorldAttributesRequestSubject unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
