# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_app_bots500_response import AppsListAppBots500Response
from snyk_python_sdk import configuration


class TestAppsListAppBots500Response(unittest.TestCase):
    """AppsListAppBots500Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
