# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.image_relationships_image_target_refs import ImageRelationshipsImageTargetRefs
from snyk_python_sdk import configuration


class TestImageRelationshipsImageTargetRefs(unittest.TestCase):
    """ImageRelationshipsImageTargetRefs unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
