# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.issues_list_by_org_id_response_jsonapi import IssuesListByOrgIdResponseJsonapi
from snyk_python_sdk import configuration


class TestIssuesListByOrgIdResponseJsonapi(unittest.TestCase):
    """IssuesListByOrgIdResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
