# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_revoke_bot_authorization404_response_errors_item_source import AppsRevokeBotAuthorization404ResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestAppsRevokeBotAuthorization404ResponseErrorsItemSource(unittest.TestCase):
    """AppsRevokeBotAuthorization404ResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
