# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.service_accounts_update_organization_service_account_name_request_data import ServiceAccountsUpdateOrganizationServiceAccountNameRequestData
from snyk_python_sdk import configuration


class TestServiceAccountsUpdateOrganizationServiceAccountNameRequestData(unittest.TestCase):
    """ServiceAccountsUpdateOrganizationServiceAccountNameRequestData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
