# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_create_new_app_for_organization404_response_errors_item_source import AppsCreateNewAppForOrganization404ResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestAppsCreateNewAppForOrganization404ResponseErrorsItemSource(unittest.TestCase):
    """AppsCreateNewAppForOrganization404ResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
