# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.issues_get_by_issue_id401_response_jsonapi import IssuesGetByIssueId401ResponseJsonapi
from snyk_python_sdk import configuration


class TestIssuesGetByIssueId401ResponseJsonapi(unittest.TestCase):
    """IssuesGetByIssueId401ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
