# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_delete_app_by_id403_response_errors_item import AppsDeleteAppById403ResponseErrorsItem
from snyk_python_sdk import configuration


class TestAppsDeleteAppById403ResponseErrorsItem(unittest.TestCase):
    """AppsDeleteAppById403ResponseErrorsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
