# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_get_by_client_id400_response_errors_item_meta import AppsGetByClientId400ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsGetByClientId400ResponseErrorsItemMeta(unittest.TestCase):
    """AppsGetByClientId400ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
