# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_get_active_sessions400_response import AppsGetActiveSessions400Response
from snyk_python_sdk import configuration


class TestAppsGetActiveSessions400Response(unittest.TestCase):
    """AppsGetActiveSessions400Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
