# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_org_apps403_response_errors_item import AppsListOrgApps403ResponseErrorsItem
from snyk_python_sdk import configuration


class TestAppsListOrgApps403ResponseErrorsItem(unittest.TestCase):
    """AppsListOrgApps403ResponseErrorsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
