# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_revoke_by_install_id403_response_errors_item import AppsRevokeByInstallId403ResponseErrorsItem
from snyk_python_sdk import configuration


class TestAppsRevokeByInstallId403ResponseErrorsItem(unittest.TestCase):
    """AppsRevokeByInstallId403ResponseErrorsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
