# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.orgs_list_accessible_organizations_response import OrgsListAccessibleOrganizationsResponse
from snyk_python_sdk import configuration


class TestOrgsListAccessibleOrganizationsResponse(unittest.TestCase):
    """OrgsListAccessibleOrganizationsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
