# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.service_accounts_create_group_request_data_attributes import ServiceAccountsCreateGroupRequestDataAttributes
from snyk_python_sdk import configuration


class TestServiceAccountsCreateGroupRequestDataAttributes(unittest.TestCase):
    """ServiceAccountsCreateGroupRequestDataAttributes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
