# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.delete_projects_from_collection_request_data_item import DeleteProjectsFromCollectionRequestDataItem
from snyk_python_sdk import configuration


class TestDeleteProjectsFromCollectionRequestDataItem(unittest.TestCase):
    """DeleteProjectsFromCollectionRequestDataItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
