# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_app_bots409_response import AppsListAppBots409Response
from snyk_python_sdk import configuration


class TestAppsListAppBots409Response(unittest.TestCase):
    """AppsListAppBots409Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
