# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_revoke_by_install_id404_response_errors_item_meta import AppsRevokeByInstallId404ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsRevokeByInstallId404ResponseErrorsItemMeta(unittest.TestCase):
    """AppsRevokeByInstallId404ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
