# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.slack_get_channel_name_by_id_response import SlackGetChannelNameByIdResponse
from snyk_python_sdk import configuration


class TestSlackGetChannelNameByIdResponse(unittest.TestCase):
    """SlackGetChannelNameByIdResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
