# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.coordinate import Coordinate
from snyk_python_sdk import configuration


class TestCoordinate(unittest.TestCase):
    """Coordinate unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
