# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_delete_by_app_id409_response_jsonapi import AppsDeleteByAppId409ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsDeleteByAppId409ResponseJsonapi(unittest.TestCase):
    """AppsDeleteByAppId409ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
