# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_revoke_app_by_id403_response import AppsRevokeAppById403Response
from snyk_python_sdk import configuration


class TestAppsRevokeAppById403Response(unittest.TestCase):
    """AppsRevokeAppById403Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
