# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.org_role_attributes import OrgRoleAttributes
from snyk_python_sdk import configuration


class TestOrgRoleAttributes(unittest.TestCase):
    """OrgRoleAttributes unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
