# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_user_installed_apps403_response import AppsListUserInstalledApps403Response
from snyk_python_sdk import configuration


class TestAppsListUserInstalledApps403Response(unittest.TestCase):
    """AppsListUserInstalledApps403Response unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
