# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_user_installed_apps401_response_errors_item_source import AppsListUserInstalledApps401ResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestAppsListUserInstalledApps401ResponseErrorsItemSource(unittest.TestCase):
    """AppsListUserInstalledApps401ResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
