# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.service_accounts_get_organization_account_by_id_response_data import ServiceAccountsGetOrganizationAccountByIdResponseData
from snyk_python_sdk import configuration


class TestServiceAccountsGetOrganizationAccountByIdResponseData(unittest.TestCase):
    """ServiceAccountsGetOrganizationAccountByIdResponseData unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
