# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_revoke_group_app_install500_response_jsonapi import AppsRevokeGroupAppInstall500ResponseJsonapi
from snyk_python_sdk import configuration


class TestAppsRevokeGroupAppInstall500ResponseJsonapi(unittest.TestCase):
    """AppsRevokeGroupAppInstall500ResponseJsonapi unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
