# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_user_installed_apps401_response_errors_item_meta import AppsListUserInstalledApps401ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsListUserInstalledApps401ResponseErrorsItemMeta(unittest.TestCase):
    """AppsListUserInstalledApps401ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
