# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_manage_client_secrets403_response_errors_item_meta import AppsManageClientSecrets403ResponseErrorsItemMeta
from snyk_python_sdk import configuration


class TestAppsManageClientSecrets403ResponseErrorsItemMeta(unittest.TestCase):
    """AppsManageClientSecrets403ResponseErrorsItemMeta unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
