# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_list_org_apps404_response_errors_item import AppsListOrgApps404ResponseErrorsItem
from snyk_python_sdk import configuration


class TestAppsListOrgApps404ResponseErrorsItem(unittest.TestCase):
    """AppsListOrgApps404ResponseErrorsItem unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
