# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.issues_get_by_id403_response_errors_item_source import IssuesGetById403ResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestIssuesGetById403ResponseErrorsItemSource(unittest.TestCase):
    """IssuesGetById403ResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
