# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.apps_revoke_group_app_install403_response_errors_item_source import AppsRevokeGroupAppInstall403ResponseErrorsItemSource
from snyk_python_sdk import configuration


class TestAppsRevokeGroupAppInstall403ResponseErrorsItemSource(unittest.TestCase):
    """AppsRevokeGroupAppInstall403ResponseErrorsItemSource unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
