# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest

import snyk_python_sdk
from snyk_python_sdk.model.paginated_links import PaginatedLinks
from snyk_python_sdk import configuration


class TestPaginatedLinks(unittest.TestCase):
    """PaginatedLinks unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
