# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import snyk_python_sdk
from snyk_python_sdk.paths.groups_group_id_issues_issue_id import get
from snyk_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestGroupsGroupIdIssuesIssueId(ApiTestMixin, unittest.TestCase):
    """
    GroupsGroupIdIssuesIssueId unit test stubs
        Get an issue
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200




if __name__ == '__main__':
    unittest.main()
