# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.apps_get_by_app_id403_response_errors import AppsGetByAppId403ResponseErrors
from snyk_python_sdk.pydantic.apps_get_by_app_id403_response_jsonapi import AppsGetByAppId403ResponseJsonapi

class AppsGetByAppId403Response(BaseModel):
    errors: AppsGetByAppId403ResponseErrors = Field(alias='errors')

    jsonapi: AppsGetByAppId403ResponseJsonapi = Field(alias='jsonapi')
    class Config:
        arbitrary_types_allowed = True
