# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.apps_manage_client_secrets401_response_errors import AppsManageClientSecrets401ResponseErrors
from snyk_python_sdk.pydantic.apps_manage_client_secrets401_response_jsonapi import AppsManageClientSecrets401ResponseJsonapi

class AppsManageClientSecrets401Response(BaseModel):
    errors: AppsManageClientSecrets401ResponseErrors = Field(alias='errors')

    jsonapi: AppsManageClientSecrets401ResponseJsonapi = Field(alias='jsonapi')
    class Config:
        arbitrary_types_allowed = True
