# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.apps_get_active_sessions500_response_errors import AppsGetActiveSessions500ResponseErrors
from snyk_python_sdk.pydantic.apps_get_active_sessions500_response_jsonapi import AppsGetActiveSessions500ResponseJsonapi

class AppsGetActiveSessions500Response(BaseModel):
    errors: AppsGetActiveSessions500ResponseErrors = Field(alias='errors')

    jsonapi: AppsGetActiveSessions500ResponseJsonapi = Field(alias='jsonapi')
    class Config:
        arbitrary_types_allowed = True
