# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.apps_list_org_creations404_response_errors import AppsListOrgCreations404ResponseErrors
from snyk_python_sdk.pydantic.apps_list_org_creations404_response_jsonapi import AppsListOrgCreations404ResponseJsonapi

class AppsListOrgCreations404Response(BaseModel):
    errors: AppsListOrgCreations404ResponseErrors = Field(alias='errors')

    jsonapi: AppsListOrgCreations404ResponseJsonapi = Field(alias='jsonapi')
    class Config:
        arbitrary_types_allowed = True
