# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.apps_list_org_apps400_response_errors import AppsListOrgApps400ResponseErrors
from snyk_python_sdk.pydantic.apps_list_org_apps400_response_jsonapi import AppsListOrgApps400ResponseJsonapi

class AppsListOrgApps400Response(BaseModel):
    errors: AppsListOrgApps400ResponseErrors = Field(alias='errors')

    jsonapi: AppsListOrgApps400ResponseJsonapi = Field(alias='jsonapi')
    class Config:
        arbitrary_types_allowed = True
