# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.apps_create_new_app_for_organization_response_errors import AppsCreateNewAppForOrganizationResponseErrors
from snyk_python_sdk.pydantic.apps_create_new_app_for_organization_response_jsonapi import AppsCreateNewAppForOrganizationResponseJsonapi

class AppsCreateNewAppForOrganizationResponse(BaseModel):
    errors: AppsCreateNewAppForOrganizationResponseErrors = Field(alias='errors')

    jsonapi: AppsCreateNewAppForOrganizationResponseJsonapi = Field(alias='jsonapi')
    class Config:
        arbitrary_types_allowed = True
