# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.coordinate_v_two_remedies import CoordinateVTwoRemedies
from snyk_python_sdk.pydantic.coordinate_v_two_representations import CoordinateVTwoRepresentations

class CoordinateVTwo(BaseModel):
    representations: CoordinateVTwoRepresentations = Field(alias='representations')

    remedies: typing.Optional[CoordinateVTwoRemedies] = Field(None, alias='remedies')
    class Config:
        arbitrary_types_allowed = True
