# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.custom_base_image_attributes import CustomBaseImageAttributes

class CustomBaseImagePostRequestData(BaseModel):
    attributes: CustomBaseImageAttributes = Field(alias='attributes')

    # This should always be \"custom_base_image\"
    type: str = Field(alias='type')
    class Config:
        arbitrary_types_allowed = True
