# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CycloneDxComponent(BaseModel):
    version: typing.Optional[str] = Field(None, alias='version')

    bom-ref_: typing.Optional[str] = Field(None, alias='bom-ref')

    name: typing.Optional[str] = Field(None, alias='name')

    purl: typing.Optional[str] = Field(None, alias='purl')

    type: typing.Optional[str] = Field(None, alias='type')
    class Config:
        arbitrary_types_allowed = True
