# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.issue_relationships_ignore import IssueRelationshipsIgnore
from snyk_python_sdk.pydantic.issue_relationships_organization import IssueRelationshipsOrganization
from snyk_python_sdk.pydantic.issue_relationships_scan_item import IssueRelationshipsScanItem
from snyk_python_sdk.pydantic.issue_relationships_test_executions import IssueRelationshipsTestExecutions

class IssueRelationships(BaseModel):
    organization: IssueRelationshipsOrganization = Field(alias='organization')

    scan_item: IssueRelationshipsScanItem = Field(alias='scan_item')

    ignore: typing.Optional[IssueRelationshipsIgnore] = Field(None, alias='ignore')

    test_executions: typing.Optional[IssueRelationshipsTestExecutions] = Field(None, alias='test_executions')
    class Config:
        arbitrary_types_allowed = True
