# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.issues_list_by_org_id404_response_errors import IssuesListByOrgId404ResponseErrors
from snyk_python_sdk.pydantic.issues_list_by_org_id404_response_jsonapi import IssuesListByOrgId404ResponseJsonapi

class IssuesListByOrgId404Response(BaseModel):
    errors: IssuesListByOrgId404ResponseErrors = Field(alias='errors')

    jsonapi: IssuesListByOrgId404ResponseJsonapi = Field(alias='jsonapi')
    class Config:
        arbitrary_types_allowed = True
