# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.latest_dependency_total import LatestDependencyTotal
from snyk_python_sdk.pydantic.latest_issue_counts import LatestIssueCounts

class ProjectsListForOrgResponseDataItemMeta(BaseModel):
    # The date that the project was last uploaded and monitored using cli.
    cli_monitored_at: typing.Optional[typing.Optional[datetime]] = Field(None, alias='cli_monitored_at')

    latest_dependency_total: typing.Optional[LatestDependencyTotal] = Field(None, alias='latest_dependency_total')

    latest_issue_counts: typing.Optional[LatestIssueCounts] = Field(None, alias='latest_issue_counts')
    class Config:
        arbitrary_types_allowed = True
