# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from snyk_python_sdk.pydantic.resolution_type_def import ResolutionTypeDef

class Resolution(BaseModel):
    # The time when this issue was resolved.
    resolved_at: datetime = Field(alias='resolved_at')

    type: ResolutionTypeDef = Field(alias='type')

    # Optional details about the resolution. Used by Snyk Cloud so far.
    details: typing.Optional[str] = Field(None, alias='details')
    class Config:
        arbitrary_types_allowed = True
