# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import snyk_python_sdk
from snyk_python_sdk.paths.self_apps_app_id import delete
from snyk_python_sdk import configuration, schemas, api_client

from .. import ApiTestMixin


class TestSelfAppsAppId(ApiTestMixin, unittest.TestCase):
    """
    SelfAppsAppId unit test stubs
        Revoke an app
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 204
    response_body = ''


if __name__ == '__main__':
    unittest.main()
