# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_list_org_installs409_response_errors import AppsListOrgInstalls409ResponseErrors
from snyk_python_sdk.type.apps_list_org_installs409_response_jsonapi import AppsListOrgInstalls409ResponseJsonapi

class RequiredAppsListOrgInstalls409Response(TypedDict):
    errors: AppsListOrgInstalls409ResponseErrors

    jsonapi: AppsListOrgInstalls409ResponseJsonapi

class OptionalAppsListOrgInstalls409Response(TypedDict, total=False):
    pass

class AppsListOrgInstalls409Response(RequiredAppsListOrgInstalls409Response, OptionalAppsListOrgInstalls409Response):
    pass
