# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_delete_by_app_id500_response_errors import AppsDeleteByAppId500ResponseErrors
from snyk_python_sdk.type.apps_delete_by_app_id500_response_jsonapi import AppsDeleteByAppId500ResponseJsonapi

class RequiredAppsDeleteByAppId500Response(TypedDict):
    errors: AppsDeleteByAppId500ResponseErrors

    jsonapi: AppsDeleteByAppId500ResponseJsonapi

class OptionalAppsDeleteByAppId500Response(TypedDict, total=False):
    pass

class AppsDeleteByAppId500Response(RequiredAppsDeleteByAppId500Response, OptionalAppsDeleteByAppId500Response):
    pass
