# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_get_by_client_id500_response_errors_item import AppsGetByClientId500ResponseErrorsItem

AppsGetByClientId500ResponseErrors = typing.List[AppsGetByClientId500ResponseErrorsItem]
