# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_manage_client_secret_for_snyk_app403_response_errors import AppsManageClientSecretForSnykApp403ResponseErrors
from snyk_python_sdk.type.apps_manage_client_secret_for_snyk_app403_response_jsonapi import AppsManageClientSecretForSnykApp403ResponseJsonapi

class RequiredAppsManageClientSecretForSnykApp403Response(TypedDict):
    errors: AppsManageClientSecretForSnykApp403ResponseErrors

    jsonapi: AppsManageClientSecretForSnykApp403ResponseJsonapi

class OptionalAppsManageClientSecretForSnykApp403Response(TypedDict, total=False):
    pass

class AppsManageClientSecretForSnykApp403Response(RequiredAppsManageClientSecretForSnykApp403Response, OptionalAppsManageClientSecretForSnykApp403Response):
    pass
