# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_get_by_app_id404_response_errors_item import AppsGetByAppId404ResponseErrorsItem

AppsGetByAppId404ResponseErrors = typing.List[AppsGetByAppId404ResponseErrorsItem]
