# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_get_active_sessions403_response_errors import AppsGetActiveSessions403ResponseErrors
from snyk_python_sdk.type.apps_get_active_sessions403_response_jsonapi import AppsGetActiveSessions403ResponseJsonapi

class RequiredAppsGetActiveSessions403Response(TypedDict):
    errors: AppsGetActiveSessions403ResponseErrors

    jsonapi: AppsGetActiveSessions403ResponseJsonapi

class OptionalAppsGetActiveSessions403Response(TypedDict, total=False):
    pass

class AppsGetActiveSessions403Response(RequiredAppsGetActiveSessions403Response, OptionalAppsGetActiveSessions403Response):
    pass
