# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_create_install_secret_request_data import AppsCreateInstallSecretRequestData

class RequiredAppsCreateInstallSecretRequest(TypedDict):
    data: AppsCreateInstallSecretRequestData

class OptionalAppsCreateInstallSecretRequest(TypedDict, total=False):
    pass

class AppsCreateInstallSecretRequest(RequiredAppsCreateInstallSecretRequest, OptionalAppsCreateInstallSecretRequest):
    pass
