# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_revoke_bot_authorization409_response_errors import AppsRevokeBotAuthorization409ResponseErrors
from snyk_python_sdk.type.apps_revoke_bot_authorization409_response_jsonapi import AppsRevokeBotAuthorization409ResponseJsonapi

class RequiredAppsRevokeBotAuthorization409Response(TypedDict):
    errors: AppsRevokeBotAuthorization409ResponseErrors

    jsonapi: AppsRevokeBotAuthorization409ResponseJsonapi

class OptionalAppsRevokeBotAuthorization409Response(TypedDict, total=False):
    pass

class AppsRevokeBotAuthorization409Response(RequiredAppsRevokeBotAuthorization409Response, OptionalAppsRevokeBotAuthorization409Response):
    pass
