# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_revoke_user_app_session401_response_errors import AppsRevokeUserAppSession401ResponseErrors
from snyk_python_sdk.type.apps_revoke_user_app_session401_response_jsonapi import AppsRevokeUserAppSession401ResponseJsonapi

class RequiredAppsRevokeUserAppSession401Response(TypedDict):
    errors: AppsRevokeUserAppSession401ResponseErrors

    jsonapi: AppsRevokeUserAppSession401ResponseJsonapi

class OptionalAppsRevokeUserAppSession401Response(TypedDict, total=False):
    pass

class AppsRevokeUserAppSession401Response(RequiredAppsRevokeUserAppSession401Response, OptionalAppsRevokeUserAppSession401Response):
    pass
