# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_list_app_bots409_response_errors import AppsListAppBots409ResponseErrors
from snyk_python_sdk.type.apps_list_app_bots409_response_jsonapi import AppsListAppBots409ResponseJsonapi

class RequiredAppsListAppBots409Response(TypedDict):
    errors: AppsListAppBots409ResponseErrors

    jsonapi: AppsListAppBots409ResponseJsonapi

class OptionalAppsListAppBots409Response(TypedDict, total=False):
    pass

class AppsListAppBots409Response(RequiredAppsListAppBots409Response, OptionalAppsListAppBots409Response):
    pass
