# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_get_active_sessions400_response_errors import AppsGetActiveSessions400ResponseErrors
from snyk_python_sdk.type.apps_get_active_sessions400_response_jsonapi import AppsGetActiveSessions400ResponseJsonapi

class RequiredAppsGetActiveSessions400Response(TypedDict):
    errors: AppsGetActiveSessions400ResponseErrors

    jsonapi: AppsGetActiveSessions400ResponseJsonapi

class OptionalAppsGetActiveSessions400Response(TypedDict, total=False):
    pass

class AppsGetActiveSessions400Response(RequiredAppsGetActiveSessions400Response, OptionalAppsGetActiveSessions400Response):
    pass
