# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_list_user_installed_apps409_response_errors import AppsListUserInstalledApps409ResponseErrors
from snyk_python_sdk.type.apps_list_user_installed_apps409_response_jsonapi import AppsListUserInstalledApps409ResponseJsonapi

class RequiredAppsListUserInstalledApps409Response(TypedDict):
    errors: AppsListUserInstalledApps409ResponseErrors

    jsonapi: AppsListUserInstalledApps409ResponseJsonapi

class OptionalAppsListUserInstalledApps409Response(TypedDict, total=False):
    pass

class AppsListUserInstalledApps409Response(RequiredAppsListUserInstalledApps409Response, OptionalAppsListUserInstalledApps409Response):
    pass
