# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_by_install_id_response_errors import AppsByInstallIdResponseErrors
from snyk_python_sdk.type.apps_by_install_id_response_jsonapi import AppsByInstallIdResponseJsonapi

class RequiredAppsByInstallIdResponse(TypedDict):
    errors: AppsByInstallIdResponseErrors

    jsonapi: AppsByInstallIdResponseJsonapi

class OptionalAppsByInstallIdResponse(TypedDict, total=False):
    pass

class AppsByInstallIdResponse(RequiredAppsByInstallIdResponse, OptionalAppsByInstallIdResponse):
    pass
