# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_list_group_app_installs401_response_errors import AppsListGroupAppInstalls401ResponseErrors
from snyk_python_sdk.type.apps_list_group_app_installs401_response_jsonapi import AppsListGroupAppInstalls401ResponseJsonapi

class RequiredAppsListGroupAppInstalls401Response(TypedDict):
    errors: AppsListGroupAppInstalls401ResponseErrors

    jsonapi: AppsListGroupAppInstalls401ResponseJsonapi

class OptionalAppsListGroupAppInstalls401Response(TypedDict, total=False):
    pass

class AppsListGroupAppInstalls401Response(RequiredAppsListGroupAppInstalls401Response, OptionalAppsListGroupAppInstalls401Response):
    pass
