# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_create_new_app_for_organization500_response_errors import AppsCreateNewAppForOrganization500ResponseErrors
from snyk_python_sdk.type.apps_create_new_app_for_organization500_response_jsonapi import AppsCreateNewAppForOrganization500ResponseJsonapi

class RequiredAppsCreateNewAppForOrganization500Response(TypedDict):
    errors: AppsCreateNewAppForOrganization500ResponseErrors

    jsonapi: AppsCreateNewAppForOrganization500ResponseJsonapi

class OptionalAppsCreateNewAppForOrganization500Response(TypedDict, total=False):
    pass

class AppsCreateNewAppForOrganization500Response(RequiredAppsCreateNewAppForOrganization500Response, OptionalAppsCreateNewAppForOrganization500Response):
    pass
