# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.apps_delete_by_app_id404_response_errors import AppsDeleteByAppId404ResponseErrors
from snyk_python_sdk.type.apps_delete_by_app_id404_response_jsonapi import AppsDeleteByAppId404ResponseJsonapi

class RequiredAppsDeleteByAppId404Response(TypedDict):
    errors: AppsDeleteByAppId404ResponseErrors

    jsonapi: AppsDeleteByAppId404ResponseJsonapi

class OptionalAppsDeleteByAppId404Response(TypedDict, total=False):
    pass

class AppsDeleteByAppId404Response(RequiredAppsDeleteByAppId404Response, OptionalAppsDeleteByAppId404Response):
    pass
