# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCommonIssueModelAttributesCoordinatesItemRemediesItemDetails(TypedDict):
    pass

class OptionalCommonIssueModelAttributesCoordinatesItemRemediesItemDetails(TypedDict, total=False):
    # A minimum version to upgrade to in order to remedy the issue.
    upgrade_package: str

class CommonIssueModelAttributesCoordinatesItemRemediesItemDetails(RequiredCommonIssueModelAttributesCoordinatesItemRemediesItemDetails, OptionalCommonIssueModelAttributesCoordinatesItemRemediesItemDetails):
    pass
