# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.coordinate_representations import CoordinateRepresentations
from snyk_python_sdk.type.remedy import Remedy

class RequiredCoordinate(TypedDict):
    pass

class OptionalCoordinate(TypedDict, total=False):
    is_fixable_manually: bool

    is_fixable_snyk: bool

    is_fixable_upstream: bool

    is_patchable: bool

    is_pinnable: bool

    is_upgradeable: bool

    reachability: str

    remedies: typing.List[Remedy]

    representations: CoordinateRepresentations

class Coordinate(RequiredCoordinate, OptionalCoordinate):
    pass
