# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCustomBaseImageSnapshot(TypedDict):
    pass

class OptionalCustomBaseImageSnapshot(TypedDict, total=False):
    group_id: str

    include_in_recommendations: bool

    org_id: str

    project_id: str

    repository: str

    tag: str

class CustomBaseImageSnapshot(RequiredCustomBaseImageSnapshot, OptionalCustomBaseImageSnapshot):
    pass
