# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.cyclone_dx_component import CycloneDxComponent
from snyk_python_sdk.type.cyclone_dx_dependency import CycloneDxDependency
from snyk_python_sdk.type.cyclone_dx_metadata import CycloneDxMetadata

class RequiredCycloneDxXmlDocument(TypedDict):
    # A list of included software components
    components: typing.List[CycloneDxComponent]

    dependencies: typing.List[CycloneDxDependency]

    metadata: CycloneDxMetadata

class OptionalCycloneDxXmlDocument(TypedDict, total=False):
    pass

class CycloneDxXmlDocument(RequiredCycloneDxXmlDocument, OptionalCycloneDxXmlDocument):
    pass
