# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.group_iac_settings_request_attributes import GroupIacSettingsRequestAttributes

class RequiredGroupIacSettingsRequest(TypedDict):
    attributes: GroupIacSettingsRequestAttributes

    # Content type
    type: str

class OptionalGroupIacSettingsRequest(TypedDict, total=False):
    pass

class GroupIacSettingsRequest(RequiredGroupIacSettingsRequest, OptionalGroupIacSettingsRequest):
    pass
