# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.org_iac_settings_request import OrgIacSettingsRequest

class RequiredIacSettingsUpdateForOrgRequest(TypedDict):
    pass

class OptionalIacSettingsUpdateForOrgRequest(TypedDict, total=False):
    data: OrgIacSettingsRequest

class IacSettingsUpdateForOrgRequest(RequiredIacSettingsUpdateForOrgRequest, OptionalIacSettingsUpdateForOrgRequest):
    pass
