# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.issues_by_group_id403_response_errors import IssuesByGroupId403ResponseErrors
from snyk_python_sdk.type.issues_by_group_id403_response_jsonapi import IssuesByGroupId403ResponseJsonapi

class RequiredIssuesByGroupId403Response(TypedDict):
    errors: IssuesByGroupId403ResponseErrors

    jsonapi: IssuesByGroupId403ResponseJsonapi

class OptionalIssuesByGroupId403Response(TypedDict, total=False):
    pass

class IssuesByGroupId403Response(RequiredIssuesByGroupId403Response, OptionalIssuesByGroupId403Response):
    pass
