# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.scan_item_type import ScanItemType

class RequiredIssueRelationshipsScanItemData(TypedDict):
    id: str

    type: ScanItemType

class OptionalIssueRelationshipsScanItemData(TypedDict, total=False):
    pass

class IssueRelationshipsScanItemData(RequiredIssueRelationshipsScanItemData, OptionalIssueRelationshipsScanItemData):
    pass
