# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.member_role_relationship_data import MemberRoleRelationshipData

class RequiredMemberRoleRelationship(TypedDict):
    data: MemberRoleRelationshipData

class OptionalMemberRoleRelationship(TypedDict, total=False):
    pass

class MemberRoleRelationship(RequiredMemberRoleRelationship, OptionalMemberRoleRelationship):
    pass
