# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.org_iac_settings_response_attributes_custom_rules_parents_group_custom_rules import OrgIacSettingsResponseAttributesCustomRulesParentsGroupCustomRules

class RequiredOrgIacSettingsResponseAttributesCustomRulesParentsGroup(TypedDict):
    pass

class OptionalOrgIacSettingsResponseAttributesCustomRulesParentsGroup(TypedDict, total=False):
    custom_rules: OrgIacSettingsResponseAttributesCustomRulesParentsGroupCustomRules

    # The last time the settings were updated.
    updated: datetime

class OrgIacSettingsResponseAttributesCustomRulesParentsGroup(RequiredOrgIacSettingsResponseAttributesCustomRulesParentsGroup, OptionalOrgIacSettingsResponseAttributesCustomRulesParentsGroup):
    pass
