# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.patch_project_request_data_attributes_business_criticality import PatchProjectRequestDataAttributesBusinessCriticality
from snyk_python_sdk.type.patch_project_request_data_attributes_environment import PatchProjectRequestDataAttributesEnvironment
from snyk_python_sdk.type.patch_project_request_data_attributes_lifecycle import PatchProjectRequestDataAttributesLifecycle
from snyk_python_sdk.type.patch_project_request_data_attributes_tags import PatchProjectRequestDataAttributesTags

class RequiredPatchProjectRequestDataAttributes(TypedDict):
    pass

class OptionalPatchProjectRequestDataAttributes(TypedDict, total=False):
    tags: PatchProjectRequestDataAttributesTags

    business_criticality: PatchProjectRequestDataAttributesBusinessCriticality

    environment: PatchProjectRequestDataAttributesEnvironment

    lifecycle: PatchProjectRequestDataAttributesLifecycle

    # Test frequency of a project. Also controls when automated PRs may be created.
    test_frequency: str

class PatchProjectRequestDataAttributes(RequiredPatchProjectRequestDataAttributes, OptionalPatchProjectRequestDataAttributes):
    pass
