# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.auto_dependency_upgrade_settings import AutoDependencyUpgradeSettings
from snyk_python_sdk.type.auto_remediation_prs_settings import AutoRemediationPRsSettings
from snyk_python_sdk.type.manual_remediation_prs_settings import ManualRemediationPRsSettings
from snyk_python_sdk.type.pull_request_assignment_settings import PullRequestAssignmentSettings
from snyk_python_sdk.type.pull_requests_settings import PullRequestsSettings
from snyk_python_sdk.type.recurring_tests_settings import RecurringTestsSettings

class RequiredProjectSettings(TypedDict):
    pull_requests: PullRequestsSettings

    recurring_tests: RecurringTestsSettings

class OptionalProjectSettings(TypedDict, total=False):
    auto_dependency_upgrade: AutoDependencyUpgradeSettings

    auto_remediation_prs: AutoRemediationPRsSettings

    manual_remediation_prs: ManualRemediationPRsSettings

    pull_request_assignment: PullRequestAssignmentSettings

class ProjectSettings(RequiredProjectSettings, OptionalProjectSettings):
    pass
