# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.json_api import JsonApi
from snyk_python_sdk.type.links import Links
from snyk_python_sdk.type.projects_update_by_project_id_response_data import ProjectsUpdateByProjectIdResponseData

class RequiredProjectsUpdateByProjectIdResponse(TypedDict):
    data: ProjectsUpdateByProjectIdResponseData

    jsonapi: JsonApi

    links: Links

class OptionalProjectsUpdateByProjectIdResponse(TypedDict, total=False):
    pass

class ProjectsUpdateByProjectIdResponse(RequiredProjectsUpdateByProjectIdResponse, OptionalProjectsUpdateByProjectIdResponse):
    pass
