# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.public_target_attributes import PublicTargetAttributes
from snyk_python_sdk.type.public_target_relationships import PublicTargetRelationships

class RequiredPublicTarget(TypedDict):
    attributes: PublicTargetAttributes

    # The id of this target
    id: str

    # Content type.
    type: str

class OptionalPublicTarget(TypedDict, total=False):
    relationships: PublicTargetRelationships

class PublicTarget(RequiredPublicTarget, OptionalPublicTarget):
    pass
