# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredRecurringTestsSettings(TypedDict):
    pass

class OptionalRecurringTestsSettings(TypedDict, total=False):
    # Test frequency of a project. Also controls when automated PRs may be created.
    frequency: str

class RecurringTestsSettings(RequiredRecurringTestsSettings, OptionalRecurringTestsSettings):
    pass
