# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.relationship_data import RelationshipData
from snyk_python_sdk.type.relationship_links import RelationshipLinks
from snyk_python_sdk.type.relationship_meta import RelationshipMeta

class RequiredRelationship(TypedDict):
    data: RelationshipData

    links: RelationshipLinks

class OptionalRelationship(TypedDict, total=False):
    meta: RelationshipMeta

class Relationship(RequiredRelationship, OptionalRelationship):
    pass
