# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.remedy_metadata_data import RemedyMetadataData

class RequiredRemedyMetadata(TypedDict):
    data: RemedyMetadataData

    # A schema version identifier the metadata object validates against. Note: this information is only relevant in the domain of the API consumer: the issues system always considers metadata just as an arbitrary object. 
    schema_version: str

class OptionalRemedyMetadata(TypedDict, total=False):
    pass

class RemedyMetadata(RequiredRemedyMetadata, OptionalRemedyMetadata):
    pass
