# coding: utf-8

"""
    Snyk API

    Missing description placeholder

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from snyk_python_sdk.type.json_api import JsonApi
from snyk_python_sdk.type.links import Links
from snyk_python_sdk.type.service_accounts_get_group_service_account_response_data import ServiceAccountsGetGroupServiceAccountResponseData

class RequiredServiceAccountsGetGroupServiceAccountResponse(TypedDict):
    data: ServiceAccountsGetGroupServiceAccountResponseData

    jsonapi: JsonApi

    links: Links

class OptionalServiceAccountsGetGroupServiceAccountResponse(TypedDict, total=False):
    pass

class ServiceAccountsGetGroupServiceAccountResponse(RequiredServiceAccountsGetGroupServiceAccountResponse, OptionalServiceAccountsGetGroupServiceAccountResponse):
    pass
