# coding: utf-8

"""
    Snyk API

    Snyk helps software-driven businesses develop fast and stay secure. Continuously find and fix vulnerabilities for npm, Maven, NuGet, RubyGems, PyPI and more.

    The version of the OpenAPI document: REST
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredSeverity(TypedDict):
    pass

class OptionalSeverity(TypedDict, total=False):
    level: str

    # The CVSSv3 value of the vulnerability.
    score: typing.Optional[typing.Union[int, float]]

    # The source of this severity. The value must be the id of a referenced problem or class, in which case that problem or class is the source of this issue. If source is omitted, this severity is sourced internally in the Snyk application.
    source: str

    # The CVSSv3 value of the vulnerability.
    vector: typing.Optional[str]

class Severity(RequiredSeverity, OptionalSeverity):
    pass
